name: quiz_kelaskiwari
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/static/Nunito-ExtraLight.ttf
        - asset: fonts/Nunito/static/Nunito-ExtraLightItalic.ttf
          weight: 100
        - asset: fonts/Nunito/static/Nunito-Light.ttf
        - asset: fonts/Nunito/static/Nunito-LightItalic.ttf
          weight: 200
        - asset: fonts/Nunito/static/Nunito-Regular.ttf
        - asset: fonts/Nunito/static/Nunito-Italic.ttf
          weight: 400
        - asset: fonts/Nunito/static/Nunito-Medium.ttf
        - asset: fonts/Nunito/static/Nunito-MediumItalic.ttf
          weight: 500
        - asset: fonts/Nunito/static/Nunito-SemiBold.ttf
        - asset: fonts/Nunito/static/Nunito-SemiBoldItalic.ttf
          weight: 600
        - asset: fonts/Nunito/static/Nunito-Bold.ttf
        - asset: fonts/Nunito/static/Nunito-BoldItalic.ttf
          weight: 700
        - asset: fonts/Nunito/static/Nunito-ExtraBold.ttf
        - asset: fonts/Nunito/static/Nunito-ExtraBoldItalic.ttf
          weight: 800
        - asset: fonts/Nunito/static/Nunito-Black.ttf
        - asset: fonts/Nunito/static/Nunito-BlackItalic.ttf
          weight: 900

